config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('tables.urls', namespace='tables'))
]

tables/urls.py
from django.urls import path

from tables.apps import TablesConfig
from tables.views import HomePageView, AboutView, TableReserve, TableUpdate

app_name = TablesConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('list/', TableReserve.as_view(), name='list'),
    path('reserve/<int:pk>/', TableUpdate.as_view(), name='reserve')

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, ProfileView

app_name = UsersConfig.name


urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='login.html'), name='login'
         ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(template_name='users/register.html'), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

tables/models.py
from django.db import models
from users.models import User

NULLABLE = {"blank": True, "null": True}


class Table(models.Model):
    """
    Модель столика
    """
    table_num = models.PositiveIntegerField(
        verbose_name='Номер столика'
    )
    is_reserved = models.BooleanField(
        default=False, verbose_name='Признак брони'
    )
    time_of_reserve = models.DateTimeField(
        help_text='Введите дату в формате ГГГГ-ММ-ДД ЧЧ:ММ',
        verbose_name='Время начала брони', **NULLABLE
    )
    time_end_reserve = models.DateTimeField(
        help_text='Введите дату в формате ГГГГ-ММ-ДД ЧЧ:ММ',
        verbose_name='Время конца брони', **NULLABLE
    )
    client = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        verbose_name='Держатель брони', **NULLABLE
    )
    user_phone = models.CharField(
        max_length=15, verbose_name='Телефон клиента',
        **NULLABLE
    )
    user_name = models.CharField(
        max_length=50, verbose_name='Имя клиента',
        **NULLABLE
    )

    class Meta:
        verbose_name = 'столик'
        verbose_name_plural = 'столики'

        def __str__(self):
            return f'Столик номер {self.table_num}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    модель клиента
    """
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    phone = models.CharField(max_length=12, verbose_name='Телефон клиента')
    name = models.CharField(max_length=50, verbose_name='Имя клиента')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

        def __str__(self):
            return f'{self.name} - {self.phone}'

users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django import forms

from tables.models import Table
from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'phone', 'password1', 'password2')
        labels = {
                'email': 'Почта',
                'password1': 'Пароль',
                'password2': 'Подтвердите пароль',
            }
        help_texts = {
                'email': 'Введите вашу почту',
                'name': 'Используется для брони',
                'password1': 'Введите ваш пароль',
                'password2': 'Повторите ваш пароль',
            }


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'phone')
        labels = {
                'email': 'Почта',
                'name': 'Имя',
                'phone': 'Телефон',
            }


class TableForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = '__all__'

tables/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, UpdateView

from tables.models import Table
from tables.services import reserve_end


class HomePageView(TemplateView):
    template_name = 'home.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class TableReserve(ListView):
    model = Table
    queryset = Table.objects.all().order_by('pk')

    def setup(self, request, *args, **kwargs):
        reserve_end()
        super().setup(request, *args, **kwargs)


class TableUpdate(UpdateView):
    model = Table
    fields = ['time_of_reserve', 'time_end_reserve', 'user_phone', 'user_name']
    success_url = reverse_lazy('tables:list')

    def form_valid(self, form):
        table = form.save()
        user = self.request.user
        table.client = user
        table.user_phone = user.phone
        table.user_name = user.name
        table.is_reserved = True
        table.save()
        return super().form_valid(form)

users/views.py
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy
from users.forms import UserRegisterForm, UserProfileForm, TableForm
from django.forms import inlineformset_factory

from users.models import User
from tables.models import Table


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')




class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        tables = Table.objects.filter(client=self.request.user)
        for table in tables:
            if table.client:
                context_data['table'] = table
        context_data['current_user'] = self.request.user
        TableFormset = inlineformset_factory(
            User, Table, form=TableForm, extra=0
        )
        if self.request.method == 'POST':
            context_data['formset'] = TableFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data['formset'] = TableFormset(instance=self.object)
        return context_data

tables/templates/about.html
{% extends 'base.html' %}
{% block block %}
<h2 class="text-center text-white">О нас</h2>
<div class="container">
  <ul class="list-group list-group-horizontal py-5">
    <li class="list-group-item">История нашего ресторана:</li>
    <li class="list-group-item">Наш ресторан радует вас соей атмосферой и кухней уже 5 лет. А начиналось
    все с желания моей жены удивить всех своими познаниями в кулинарии! И вот, оглядываясь
    назад я могу с уверенностью сказать что это еще не предел наших возможностей! Это только начало!!!</li>
  </ul>
  <ul class="list-group list-group-horizontal-sm py-5">
    <li class="list-group-item">Наши миссии и ценности:</li>
    <li class="list-group-item">Главная наша миссия - донести до народа насколько вкусной и необычной может быть
      привычная всем домашняя кухня! А главня ценность, это не изменять себе и не поддаваться на изменчивость трендов!</li>
  </ul>
  <ul class="list-group list-group-horizontal-md py-5">
    <li class="list-group-item">Наша команда:</li>
    <li class="list-group-item">Для вас всегда рады стараться все люди из нашего коллектива, это директор, в лице моей
    жены, управляющий - я сам, и бригада поваров, которые переняли все секреты и рецепты блюд готовишихся в нашей семье!</li>
  </ul>
</div>

{% endblock %}

tables/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{title}}</title>



    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css'%}" rel="stylesheet">
</head>

<body class="bg-dark">
{% include 'includes/nav_bar.html' %}
{% block block %}
{% endblock %}

<footer class="text-muted">
    <div class="container">
        <p>&copy; {% now 'Y'%} </p>
    </div>
</footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

tables/templates/home.html
{% extends 'base.html' %}
{% block block %}

<section class="py-5">
    <div class="col-md-8 py-5 mx-auto text-center">
                    <h1 class="text-white">HOME - RESTAURANT</h1>
                    <p class="text-white">Ресторан домашней кухни</p>
    </div>
</section>
<h3 class="py-2 text-center lead text-white">
    Мы - ресторан домашней кухни "Home - Restaraunt"<br>
    У нас очень уютная и приятная домашняя атмосфера<br>
    А главное, вкусно как ДОМА!!!
</h3>
<p class="text-center text-white py-3">
    На нашем сайте вы можете забронировать столик на удобное для вас время<br>
    <a href="{% url 'tables:list' %}" class="btn btn-lg bg-white text-dark">Забронировать</a>
</p>
<section class="py-5 col-12 text-center">
    <div class="row">
      <div class="col-sm-6">
        <div class="card bg-dark">
          <div class="card-body">
            <h5 class="card-title text-white">Контактная информация</h5>
            <p class="card-text text-dark">Ресепшн: +7-999-123-45-67</p>
            <p class="card-text text-white">Ресепшн: +7-999-123-45-67</p>
            <p class="card-text text-dark">Ресепшн: +7-999-123-45-67</p>
            <p class="card-text text-white">Наш адрес: Ул. Пушкина, дом 2</p>
            <p class="card-text text-dark">Ресепшн: +7-999-123-45-67</p>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card bg-dark">
          <div class="card-body">
            <h5 class="card-title text-white">Обратная связь</h5>
            <form action="" method="get">
                <input class="form-control mb-2" name="name" placeholder="Ваше имя" />
                <input type="email" class="form-control mb-2" name="email" placeholder="Ваша почта" />
                <textarea class="form-control mb-2" name="message" placeholder="Текст сообщения"></textarea>
                <button type="submit" class="btn btn-lg bg-white form-control">Отправить</button>
            </form>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}

tables/templates/includes/nav_bar.html
<header>
    <div class="collapse bg-black" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">HOME - RESTAURANT</h4>
                    <p class="text-muted">Ресторан домашней кухни</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Навигация</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'tables:home' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'tables:about' %}" class="text-white">О ресторане</a></li>
                        <li><a href="{% url 'tables:list' %}" class="text-white">Бронирование столиков</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'users:profile' %}" class="text-white">Личный кабинет</a></li>
                        <li><form action="{% url 'users:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="bg-dark text-white border-0" type="submit">Выйти</button>
                            </form>
                        </li>
                        {% else %}
                        <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                        <li><a href="{% url 'users:register' %}" class="text-white">Зарегестрироваться</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-black box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

tables/templates/tables/table_form.html
{% extends 'base.html' %}
{% block block %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Забронировать столик номер: {{ object.table_num }}
                    </h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Забронировать</button>
                        <a href="{% url 'tables:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tables/templates/tables/table_list.html
{% extends 'base.html' %}
{% block block %}
<center>
  <form class="form-control col-6">
      <h3>Выберите столик для бронирования</h3><br>
      (В списке показаны только столики доступные для бронирования)
              {% for table in object_list %}
                {% if not table.is_reserved %}
                  <div class="list-group">
                      <a href="{% url 'tables:reserve' table.pk %}" class="list-group-item list-group-item-action" aria-current="true">
                        Забронировать столик номер: {{ table.table_num }}
                      </a>
                  </div>
                {% endif %}
              {% endfor %}
  </form>
</center>
{% endblock %}

users/templates/login.html
{% extends 'base.html' %}
{% block block %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Вход</h3>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Войти</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block block %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}
{% block block %}
<div class="col-12">
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Профиль
                    </h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Текущее бронирование
                    </h3>
                </div>
                <div class="card-body">
                        {% if table.client == current_user %}
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                        {{ formset.as_p}}
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </form>
                        {% else %}
                            <h3>У вас нет текущего бронирования</h3>
                        {% endif %}
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                 <div class="card-header">
                     <h3 class="card-title">История Бронирований</h3>
                 </div>
                 <div class="card-body">
                    <div class="list-group">

                    </div>
                 </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}